apiVersion: v1
kind: Namespace
metadata:
  name: appstudio-grafana-datasource-exporter
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exporter-sa
  namespace: appstudio-grafana-datasource-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exporter-cluster-role
rules:
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanas
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exporter-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: exporter-cluster-role
subjects:
- kind: ServiceAccount
  name: exporter-sa
  namespace: appstudio-grafana-datasource-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-datasource-exporter
  name: exporter-service
  namespace: appstudio-grafana-datasource-exporter
spec:
  ports:
  - name: http
    port: 8090
    targetPort: http
  selector:
    app: grafana-datasource-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter-service-deployment
  namespace: appstudio-grafana-datasource-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-datasource-exporter
  template:
    metadata:
      labels:
        app: grafana-datasource-exporter
    spec:
      containers:
      - image: quay.io/redhat-appstudio/o11y-prometheus-exporters:v0.1
        name: grafana-datasource-exporter
        ports:
        - containerPort: 8090
          name: http
        resources:
          limits:
            cpu: 0m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 10Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      serviceAccountName: exporter-sa
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-reader-test
  namespace: appstudio-grafana-datasource-exporter
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app: grafana-datasource-exporter
